services:
  qdrant:
    build:
      context: .
      dockerfile: src/qdrant_service/Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT__STORAGE__ON_DISK_PAYLOAD=true
    volumes:
      - ./qdrant_data:/qdrant/qdrant_data
    networks:
      - chatbot

  ingestionrag:
    build: 
      context: .
      dockerfile: src/ingestionrag_service/Dockerfile
    runtime: nvidia
    volumes:
      - ./docs:/docs:ro
    networks:
      - chatbot

  vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES= all
      - PYTORCH_ALLOC_CONF=expandable_segments:True
    volumes:
      - ./model_weights:/data
      - ./models:/models
    ports:
      - "8222:8000"
    command: >
      --model /models/main_model
      --served-model-name main_model
      --max-model-len 4096
    networks:
      - chatbot


  mlflow-server:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: >
      sh -c "pip install mlflow && 
      mlflow server 
      --host 0.0.0.0 
      --port 5000 
      --backend-store-uri sqlite:////mlruns/mlflow.db 
      --artifacts-destination /mlruns/artifacts 
      --serve-artifacts
      --allowed-hosts '*'"
    networks:
      - chatbot

  mlflow-app:
    build:  
      context: .
      dockerfile: src/mlflow_service/Dockerfile
    container_name: mlflow-app
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN:-}
      - HF_TOKEN=${HF_TOKEN:-}
    depends_on:
      - mlflow-server
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/huggingface/hub
      - /mlruns/artifacts/
      - ./models:/models
    command: uv run -m main
    networks:
      - chatbot
   
  app:
    build:
      context: .
      dockerfile: src/agent/Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    networks:
      - chatbot

networks:
  chatbot:
    driver: bridge
